# -*- coding: utf-8 -*-
"""prediccion_8avos_final_corregido.ipynb

Automatically generated by Colab.

Original file is located at:
    https://colab.research.google.com/drive/1tty9I-ft1MIAo_2pf8Y_xZz0sgSkCoFP
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from collections import defaultdict  
import warnings
warnings.filterwarnings('ignore')

print("🚀 PREDICCIÓN DE CLASIFICADOS A OCTAVOS DE FINAL - MUNDIAL 2026")
print("="*70 + "\n")

# ============================================================
# 1. CARGA Y LIMPIEZA DE DATOS
# ============================================================

base_path = '/content/drive/MyDrive/Simulaciones_Mundial/Data'

cruces_raw = pd.read_csv(f"{base_path}/cruces_16avos.csv", sep=';')
datos_historicos = pd.read_csv(f"{base_path}/datos_historicos.csv")
datos_mundial = pd.read_csv(f"{base_path}/datos_mundial.csv")
ranking_fifa = pd.read_csv(f"{base_path}/ranking_fifa.csv")
transfermarkt = pd.read_csv(f"{base_path}/transfermarkt.csv")

# ============================================================
# 2. LIMPIEZA DE NOMBRES DE EQUIPOS
# ============================================================

def clean_name(name):
    name = str(name).strip()
    replacements = {
        'Estados Unidos': 'EE. UU.',
        'USA': 'EE. UU.',
        'Bosnia y Herzegovina': 'Bosnia-Herzegovina',
        'Bosnia': 'Bosnia-Herzegovina',
        'República de Corea': 'Corea del Sur',
        'RI de Irán': 'Irán',
        'Islas de Cabo Verde': 'Cabo Verde',
        'Cabo Verde': 'Cabo Verde',
        'Côte d\'Ivoire': 'Costa de Marfil',
        'Congo': 'RD Congo',
        'República Democrática del Congo': 'RD Congo',
        'República del Congo': 'Congo',
    }
    for old, new in replacements.items():
        name = name.replace(old, new)
    return name

if 'País' in ranking_fifa.columns:
    ranking_fifa = ranking_fifa.rename(columns={'País': 'Equipo'})

for df in [datos_historicos, datos_mundial, ranking_fifa, transfermarkt]:
    if 'Equipo' in df.columns:
        df['Equipo'] = df['Equipo'].apply(clean_name)
    if 'Equipo_Local' in df.columns:
        df['Equipo_Local'] = df['Equipo_Local'].apply(clean_name)
        df['Equipo_Visitante'] = df['Equipo_Visitante'].apply(clean_name)

cruces_raw['Partido'] = cruces_raw['Partido'].apply(clean_name)

print("✅ Nombres normalizados")

# ============================================================
# 3. CONSTRUCCIÓN DEL DATASET DE EQUIPOS (ESTADÍSTICAS)
# ============================================================

def get_numeric(df):
    return df[['Equipo'] + df.select_dtypes(include=[np.number]).columns.tolist()]

stats = (get_numeric(ranking_fifa)
         .merge(get_numeric(transfermarkt), on='Equipo', how='left')
         .merge(get_numeric(datos_mundial), on='Equipo', how='left'))
stats = stats.fillna(0)

# Verificar equipos faltantes
equipos_cruces = set()
for partido in cruces_raw['Partido']:
    parts = re.split(r'\s*vs\.?|\s*[–—-]\s*', partido)
    for p in parts:
        p = p.strip()
        if p:
            equipos_cruces.add(clean_name(p))

faltantes = [eq for eq in equipos_cruces if eq not in stats['Equipo'].values]
if faltantes:
    print(f"⚠️ Equipos sin estadísticas: {faltantes}. Se añadirán con valores por defecto.")
    for eq in faltantes:
        new_row = {'Equipo': eq}
        for col in stats.columns:
            if col != 'Equipo':
                new_row[col] = 0
        stats = pd.concat([stats, pd.DataFrame([new_row])], ignore_index=True)
    stats = stats.fillna(0)

print("📊 Estadísticas de equipos listas")

# ============================================================
# 4. ENTRENAMIENTO DEL MODELO (RANDOM FOREST)
# ============================================================

train_data = []
for _, row in datos_historicos.iterrows():
    h = row['Equipo_Local']
    a = row['Equipo_Visitante']
    s_h = stats[stats['Equipo'] == h]
    s_a = stats[stats['Equipo'] == a]
    if s_h.empty or s_a.empty:
        continue
    s_h = s_h.iloc[0]
    s_a = s_a.iloc[0]
    match = {}
    for col in stats.select_dtypes(include=[np.number]).columns:
        match[f"{col}_diff"] = s_h[col] - s_a[col]
    if row['Goles_Local'] > row['Goles_Visitante']:
        match['target'] = 1
    elif row['Goles_Local'] < row['Goles_Visitante']:
        match['target'] = -1
    else:
        match['target'] = 0
    train_data.append(match)

df_train = pd.DataFrame(train_data)
X = df_train.drop(columns=['target'])
y = df_train['target']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = RandomForestClassifier(n_estimators=500, max_depth=12, random_state=42)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, X_scaled, y, cv=cv, scoring='accuracy')
print(f"📊 Precisión media del modelo: {scores.mean():.2%} (+/- {scores.std():.2%})")

model.fit(X_scaled, y)
print("✅ Modelo entrenado")

# ============================================================
# 5. FUNCIÓN PARA PREDECIR UN PARTIDO (PROBABILIDADES + xG)
# ============================================================

def predict_match(home, away):
    s_h = stats[stats['Equipo'] == home]
    s_a = stats[stats['Equipo'] == away]
    if s_h.empty or s_a.empty:
        return None
    s_h = s_h.iloc[0]
    s_a = s_a.iloc[0]

    match = {}
    for col in stats.select_dtypes(include=[np.number]).columns:
        match[f"{col}_diff"] = s_h[col] - s_a[col]
    X_pred = pd.DataFrame([match])
    X_pred_scaled = scaler.transform(X_pred)

    probs = model.predict_proba(X_pred_scaled)[0]
    idx_away = np.where(model.classes_ == -1)[0][0]
    idx_draw = np.where(model.classes_ == 0)[0][0]
    idx_home = np.where(model.classes_ == 1)[0][0]
    p_away = probs[idx_away]
    p_draw = probs[idx_draw]
    p_home = probs[idx_home]

    # Goles esperados (xG) usando promedios históricos ajustados por probabilidades
    avg_goals_home = s_h.get('avg_Goles_total', 1.2)
    avg_goals_away = s_a.get('avg_Goles_total', 1.2)
    lam_home = max(0.1, avg_goals_home * (0.8 + 0.4 * p_home))
    lam_away = max(0.1, avg_goals_away * (0.8 + 0.4 * p_away))

    g_h = int(round(lam_home))
    g_a = int(round(lam_away))
    g_h = max(0, g_h)
    g_a = max(0, g_a)

    # --- NUEVO: El ganador se decide por la mayor probabilidad ---
    if p_home > p_away:
        ganador = home
    elif p_away > p_home:
        ganador = away
    else:
        # En caso de empate perfecto de probabilidades, se usa el ranking FIFA
        if s_h['Puntuación'] >= s_a['Puntuación']:
            ganador = home
        else:
            ganador = away

    return g_h, g_a, ganador, p_home, p_draw, p_away, lam_home, lam_away

# ============================================================
# 6. EXTRAER EQUIPOS DE LOS CRUCES REALES
# ============================================================

def extract_teams(match_str):
    parts = re.split(r'\s*vs\.?|\s*[–—-]\s*', match_str)
    teams = [clean_name(p.strip()) for p in parts if p.strip()]
    if len(teams) >= 2:
        return teams[0], teams[1]
    return None, None

cruces = cruces_raw.copy()
cruces[['Local', 'Visitante']] = cruces['Partido'].apply(lambda x: pd.Series(extract_teams(x)))
cruces = cruces.dropna(subset=['Local', 'Visitante'])

print("\n🏆 CRUCES DE DIECISEISAVOS DE FINAL (16vos)")
for idx, row in cruces.iterrows():
    print(f"   {idx+1:2}. {row['Local']} vs {row['Visitante']}")

# ============================================================
# 7. PREDECIR LOS GANADORES (CLASIFICADOS A OCTAVOS)
# ============================================================

print("\n" + "="*70)
print("📊 PREDICCIONES - DIECISEISAVOS DE FINAL (CLASIFICADOS A OCTAVOS)")
print("="*70 + "\n")

clasificados = []
predicciones = []

for idx, row in cruces.iterrows():
    local = row['Local']
    visitante = row['Visitante']
    result = predict_match(local, visitante)
    if result is None:
        print(f"⚠️ Datos insuficientes para {local} vs {visitante}, omitiendo...")
        continue
    g_l, g_v, ganador, p_h, p_d, p_a, xg_l, xg_v = result
    clasificados.append(ganador)
    predicciones.append({
        'Local': local,
        'Visitante': visitante,
        'xG_Local': round(xg_l, 2),
        'xG_Visitante': round(xg_v, 2),
        'Goles_Local': g_l,
        'Goles_Visitante': g_v,
        'Prob_Local': round(p_h, 3),
        'Prob_Empate': round(p_d, 3),
        'Prob_Visitante': round(p_a, 3),
        'Ganador': ganador
    })

df_pred = pd.DataFrame(predicciones)
print("📊 TABLA DE PREDICCIONES - DIECISEISAVOS")
print(df_pred.to_string(index=False))
print("\n")

print("🎯 CLASIFICADOS A OCTAVOS DE FINAL (basado en probabilidades del modelo)")
for i, eq in enumerate(clasificados, 1):
    print(f"{i:2}. {eq}")

# ============================================================
# 8. SIMULACIÓN MONTE CARLO PARA PORCENTAJES DE PASAR A OCTAVOS
# ============================================================

print("\n🔄 Calculando porcentajes de clasificación a octavos con simulación Monte Carlo (1000 iteraciones)...")

def simular_partido_poisson(home, away):
    s_h = stats[stats['Equipo'] == home]
    s_a = stats[stats['Equipo'] == away]
    if s_h.empty or s_a.empty:
        return None
    s_h = s_h.iloc[0]
    s_a = s_a.iloc[0]
    match = {}
    for col in stats.select_dtypes(include=[np.number]).columns:
        match[f"{col}_diff"] = s_h[col] - s_a[col]
    X_pred = pd.DataFrame([match])
    X_pred_scaled = scaler.transform(X_pred)
    probs = model.predict_proba(X_pred_scaled)[0]
    p_home = probs[np.where(model.classes_ == 1)[0][0]]
    p_away = probs[np.where(model.classes_ == -1)[0][0]]
    lam_home = max(0.1, 1.2 + p_home * 2.0)
    lam_away = max(0.1, 1.2 + p_away * 2.0)
    g_h = np.random.poisson(lam_home)
    g_a = np.random.poisson(lam_away)
    if g_h > g_a:
        return home
    elif g_a > g_h:
        return away
    else:
        prob_local_penal = 0.5 + (s_h['Puntuación'] - s_a['Puntuación']) / 2000.0
        prob_local_penal = np.clip(prob_local_penal, 0.2, 0.8)
        return home if np.random.rand() < prob_local_penal else away

N_SIM = 1000
contador = defaultdict(int)

for _ in range(N_SIM):
    for _, row in cruces.iterrows():
        local = row['Local']
        visitante = row['Visitante']
        ganador = simular_partido_poisson(local, visitante)
        if ganador:
            contador[ganador] += 1

total = sum(contador.values())
if total > 0:
    for eq in contador:
        contador[eq] = contador[eq] / total

df_mc = pd.DataFrame(list(contador.items()), columns=['Equipo', 'Prob_Clasificacion_Octavos'])
df_mc = df_mc.sort_values('Prob_Clasificacion_Octavos', ascending=False)

print("\n📊 PORCENTAJES DE CLASIFICACIÓN A OCTAVOS (Monte Carlo)")
print(df_mc.to_string(index=False))

# ============================================================
# 9. RESULTADO FINAL EN TABLAS
# ============================================================

print("\n" + "="*70)
print("RESULTADOS FINALES - DIECISEISAVOS DE FINAL")
print("="*70)

print("\n📌 CLASIFICADOS A OCTAVOS (basado en probabilidades)")
df_clas = pd.DataFrame({
    'Posición': range(1, len(clasificados)+1),
    'Equipo': clasificados
})
print(df_clas.to_string(index=False))

print("\n📌 TABLA DE PARTIDOS CON xG Y PROBABILIDADES")
print(df_pred[['Local', 'Visitante', 'xG_Local', 'xG_Visitante',
               'Goles_Local', 'Goles_Visitante', 'Prob_Local', 'Prob_Empate', 'Prob_Visitante', 'Ganador']].to_string(index=False))

if not df_mc.empty:
    print("\n📌 PROBABILIDADES DE CLASIFICACIÓN A OCTAVOS (Monte Carlo)")
    print(df_mc.to_string(index=False))

print("\n✅ Análisis completado.")
print("   - Datos de cruces reales de dieciseisavos de final")
print("   - Modelo Random Forest entrenado con datos históricos")
print("   - Ganador decidido por la mayor probabilidad de victoria")
print("   - Estimación de xG con distribución de Poisson (solo informativa)")
print("   - Simulación Monte Carlo para robustez (1000 iteraciones)")
